language: node_js
node_js:
  - "6"
install:
  - npm install
script:
  - cp config/secrets.js.template config/secrets.js
  - cp src/client/config/secrets.js.template src/client/config/secrets.js
  - npm run lint
  - npm run build
  - npm run coveralls
